package hotel;


import com.toedter.calendar.JCalendar;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sws
 */
public class Recherche extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Recherche
     */
    
    public Recherche() {
        super("Rechercher");
        initComponents();
        
        jCalendarControle();
        jCalendarAuListener();
        jCalendarDuListener();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcEnfant = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlNuit = new javax.swing.JLabel();
        jldestination = new javax.swing.JLabel();
        jcDestination = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcAdulte = new javax.swing.JComboBox<>();
        jbRechercher = new javax.swing.JButton();
        jlHolelTunisie = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlNbNuit = new javax.swing.JLabel();
        jcPension = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcCategorie = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));

        jPanel1.setBackground(new java.awt.Color(29, 53, 150));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jcEnfant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcEnfant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Adulte(s)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Enfant(s)");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Du");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Au");

        jlNuit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlNuit.setForeground(new java.awt.Color(240, 240, 240));
        jlNuit.setText("Nuit(s)");

        jldestination.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jldestination.setForeground(new java.awt.Color(255, 255, 255));
        jldestination.setText("Destination");

        jcDestination.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Choisir destination---", "Tunis", "Hammamet", "Sousse", "Monastir", "Mahdia", "Djerba", "Zarzis", "Tabarka", "Tozeur" }));
        jcDestination.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Categorie chambre ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Chambre 1");

        jcAdulte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcAdulte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jcAdulte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcAdulteActionPerformed(evt);
            }
        });

        jbRechercher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbRechercher.setText("Rechercher     >");
        jbRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRechercherActionPerformed(evt);
            }
        });

        jlHolelTunisie.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlHolelTunisie.setForeground(new java.awt.Color(255, 255, 255));
        jlHolelTunisie.setText("Hotel Tunisie");

        jLabel8.setBackground(new java.awt.Color(29, 53, 150));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/icone-hotel-rond.png"))); // NOI18N

        jlNbNuit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNbNuit.setForeground(new java.awt.Color(255, 255, 255));
        jlNbNuit.setText("1");

        jcPension.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcPension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petit dejeuner", "Demi pension", "Pension complete", "All inclusive" }));
        jcPension.setPreferredSize(new java.awt.Dimension(106, 21));
        jcPension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPensionActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Pension");

        jcCategorie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcCategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "standard", "luxe", "business" }));
        jcCategorie.setPreferredSize(new java.awt.Dimension(106, 21));
        jcCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCategorieActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcDestination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(218, 218, 218))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(114, 114, 114)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jlNbNuit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlNuit)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jldestination)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jcAdulte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jcEnfant, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(266, 266, 266))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jcPension, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)))
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jlHolelTunisie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlHolelTunisie, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jldestination)
                .addGap(0, 0, 0)
                .addComponent(jcDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jlNuit))
                .addGap(6, 6, 6)
                .addComponent(jlNbNuit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcPension, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcAdulte, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcEnfant, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(jbRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jbRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRechercherActionPerformed
        
        if(jcDestination.getSelectedIndex()==0)
        JOptionPane.showMessageDialog(this,"Selectionner destination","Selectionner destination",JOptionPane.ERROR_MESSAGE) ;

        else if((jdateDu.getDate()==null)||(jdateAu.getDate()==null))
        JOptionPane.showMessageDialog(this,"Choisir date","Choisir date",JOptionPane.ERROR_MESSAGE) ;
           
        else{
        String f= "yyyy-MM-dd";
        SimpleDateFormat dt = new SimpleDateFormat(f);
        String du,au;
        int x;
           du=dt.format(jdateDu.getDate());
           au=dt.format(jdateAu.getDate());
           x=(int) (jdateAu.getDate().getTime()-jdateDu.getDate().getTime()); 
            Resultat r=new Resultat(jcDestination.getSelectedItem().toString(),du,au,jcAdulte.getSelectedIndex()+jcEnfant.getSelectedIndex()+1, (int) TimeUnit.DAYS.convert(x, TimeUnit.MILLISECONDS),jcCategorie.getSelectedItem().toString(),jcPension.getSelectedIndex());
           
            r.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jbRechercherActionPerformed

    private void jcAdulteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcAdulteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcAdulteActionPerformed

    private void jcPensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcPensionActionPerformed

    private void jcCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCategorieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

   
    private void jCalendarControle(){
        
	Calendar cal = Calendar.getInstance();
        jdateDu.getJCalendar().setMinSelectableDate(cal.getTime());
  
    }
     
    private void jCalendarDuListener(){
        jdateDu.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                Calendar cal;
                cal = jdateDu.getCalendar();
                cal.add(Calendar.DATE,1);
              jdateAu.getJCalendar().setMinSelectableDate(cal.getTime());}});
    }
    
    private void jCalendarAuListener(){
        jdateAu.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
        String f= "yyyy-MM-dd";
        SimpleDateFormat dt = new SimpleDateFormat(f);
        String du,au;
        int x;
          du=dt.format(jdateDu.getDate());
           au=dt.format(jdateDu.getDate());
           x=(int)(jdateAu.getDate().getTime()-jdateDu.getDate().getTime()); 
              jlNbNuit.setText(""+(int) TimeUnit.DAYS.convert(x, TimeUnit.MILLISECONDS));
        
    }
        });}
        
   
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbRechercher;
    private javax.swing.JComboBox<String> jcAdulte;
    private javax.swing.JComboBox<String> jcCategorie;
    private javax.swing.JComboBox<String> jcDestination;
    private javax.swing.JComboBox<String> jcEnfant;
    private javax.swing.JComboBox<String> jcPension;
    private javax.swing.JLabel jlHolelTunisie;
    private javax.swing.JLabel jlNbNuit;
    private javax.swing.JLabel jlNuit;
    private javax.swing.JLabel jldestination;
    // End of variables declaration//GEN-END:variables
}
